
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: department-manager-api
    ports:
      - '7322:7322'
    environment:
      - NODE_ENV=development
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=Madara123
      - DB_DATABASE=department_manager
      - JWT_SECRET=cia_level_secret
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=department_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: